### ISSUE TITLE
General question

### ISSUE THREAD

**Issue by purplefish32** [joshglendenning/ws-tcp-relay#5]
How do I approach securing the connection to the ws-tcp-relay ?
I have a web app (react) that needs to connect the ws-tcp-relay but i dont want any old person on the internet to access the websocket

**Comment by isobit** [comment]
A very simple way to do this at the HTTP endpoint would be to use a reverse proxy with HTTP basic auth. I know [Caddy](https://caddyserver.com) (see below) provides this functionality out of the box but I imagine you could do the same with nginx or Apache. 

Another option would be to build an authentication handshake into your application protocol; in other words, allow anyone to connect but require an auth token to be sent over the websocket connection (and close the connection if the token is invalid).

Perhaps HTTP basic auth could be added to `ws-tcp-relay`, but I figure in most scenarios where endpoints are exposed to the public internet there is either auth built in to the protocol being relayed or it's already running behind a reverse proxy for firewalling/load-balancing/etc.

Specific Caddy docs:
https://caddyserver.com/docs/websocket
https://caddyserver.com/docs/basicauth

**Comment by purplefish32** [comment]
Thanks !
