### ISSUE TITLE
Please provide a concrete example

### ISSUE THREAD

**Issue by esimov** [joshglendenning/ws-tcp-relay#8]
Could you provide an example how to use this tool? Let's assume that I'm having a websocket connection already initialized and it is running on port 5000. Relying on the code I assume that it should create a tcp connection on the specified tcp address and should look at the websocket connection specified with the `-p` flag. My expectation is to receive the values (for example using `netcat` (`nc`) sent over the websocket to be consumable over tcp, in other words to receive the values from the websocket connection. But unfortunately is not happening.

**Comment by esimov** [comment]
I figured it out myself. I'm writing this down for others who are facing the same situation. 

The problem was that I was already running a webserver on the specified port and for this reason I was getting a websocket type connection error. So in order to make this tool work what you only need to do is to instantiate a websocket (not web!) server on a specific port and afterwards running `ws-tcp-relay` by pointing with the `--port` flag to that specific port. Then you can listen on the specified tcp port for the incoming messages (by using netcat for example).

**Comment by caoluong2k** [comment]
Hi @esimov, I use a web (using websocket) to send a string to the tcp server and the tcp server when receiving the string sends another string to that web. I send string to server successfully but when sending from server to web it fails. I use web-tcp-relay on the client side (on laptop). Is there a way for the web to receive the string from the server ?
